// Generated by https://quicktype.io

export interface IAPIRooms {
	jsonapi: Jsonapi;
	data:    IAPIRoomsDatum[];
	links:   DatumLinks;
}

export interface IAPIRoomsDatum {
	type:          string;
	id:            string;
	links:         DatumLinks;
	attributes:    Attributes;
	relationships: Relationships;
}

export interface Attributes {
	drupal_internal__nid:          number;
	drupal_internal__vid:          number;
	langcode:                      string;
	revision_timestamp:            string;
	revision_log:                  null;
	status:                        boolean;
	title:                         string;
	created:                       string;
	changed:                       string;
	promote:                       boolean;
	sticky:                        boolean;
	default_langcode:              boolean;
	revision_translation_affected: boolean;
	path:                          Path;
	field_kolejnosc:               number;
	field_opis:                    string;
}

export interface Path {
	alias:    null;
	pid:      null;
	langcode: string;
}

export interface DatumLinks {
	self: Self;
}

export interface Self {
	href: string;
}

export interface Relationships {
	node_type:          NodeType;
	revision_uid:       NodeType;
	uid:                NodeType;
	field_eksperymenty: FieldEksperymenty;
	field_skladniki:    FieldSkladniki;
}

export interface FieldEksperymenty {
	data:  DAT[];
	links: FieldEksperymentyLinks;
}

export interface DAT {
	type: DataType;
	id:   string;
}

export enum DataType {
	NodeEksperyment = 'node--eksperyment',
	NodeTypeNodeType = 'node_type--node_type',
	UserUser = 'user--user',
}

export interface FieldEksperymentyLinks {
	related: Self;
	self:    Self;
}

export interface FieldSkladniki {
	data:  FieldSkladnikiDatum[];
	links: FieldEksperymentyLinks;
}

export interface FieldSkladnikiDatum {
	type:  PurpleType;
	id:    string;
	meta?: DatumMeta;
}

export interface DatumMeta {
	arity: number;
}

export enum PurpleType {
	NodeSkladnik = 'node--skladnik',
}

export interface NodeType {
	data:  DAT;
	links: FieldEksperymentyLinks;
}

export interface Jsonapi {
	version: string;
	meta:    JsonapiMeta;
}

export interface JsonapiMeta {
	links: DatumLinks;
}
