// Generated by https://quicktype.io

export interface IAPITextBlocks {
	jsonapi: Jsonapi;
	data:    Datum[];
	links:   DatumLinks;
}

export interface Datum {
	type:          string;
	id:            string;
	links:         DatumLinks;
	attributes:    Attributes;
	relationships: Relationships;
}

export interface Attributes {
	drupal_internal__nid:          number;
	drupal_internal__vid:          number;
	langcode:                      string;
	revision_timestamp:            string;
	revision_log:                  null;
	status:                        boolean;
	title:                         string;
	created:                       string;
	changed:                       string;
	promote:                       boolean;
	sticky:                        boolean;
	default_langcode:              boolean;
	revision_translation_affected: boolean | null;
	path:                          Path;
	field_anchor:                  string;
	field_content:                 FieldContent;
}

export interface FieldContent {
	value:     string;
	format:    string;
	processed: string;
}

export interface Path {
	alias:    null;
	pid:      null;
	langcode: string;
}

export interface DatumLinks {
	self: Self;
}

export interface Self {
	href: string;
}

export interface Relationships {
	node_type:    NodeType;
	revision_uid: NodeType;
	uid:          NodeType;
}

export interface NodeType {
	data:  Data;
	links: NodeTypeLinks;
}

export interface Data {
	type: Type;
	id:   string;
}

export enum Type {
	NodeTypeNodeType = 'node_type--node_type',
	UserUser = 'user--user',
}

export interface NodeTypeLinks {
	related: Self;
	self:    Self;
}

export interface Jsonapi {
	version: string;
	meta:    Meta;
}

export interface Meta {
	links: DatumLinks;
}
